# syntax=docker/dockerfile:1
FROM ghcr.io/andrii-rieznik/python-gdal:py3.11-gdal3.9

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

WORKDIR /app

# Copy only requirements
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your code
COPY . .

# Start Celery worker
CMD ["celery", "-A", "tasks.worker_tasks", "worker", "--loglevel=info"]