services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - REDIS_URL=redis://default:7811262f644141d286a5dcb7478802bf@gusc1-assuring-dragon-30398.upstash.io:30398
      - PYTHONUNBUFFERED=1
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
      - api_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    environment:
      - REDIS_URL=redis://default:7811262f644141d286a5dcb7478802bf@gusc1-assuring-dragon-30398.upstash.io:30398
      - PYTHONUNBUFFERED=1
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
      - worker_data:/data
    healthcheck:
      test: ["CMD", "celery", "-A", "tasks.worker", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "30398:30398"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  api_data:
  worker_data:
  redis_data:

networks:
  default:
    driver: bridge