# syntax=docker/dockerfile:1
FROM ghcr.io/andrii-rieznik/python-gdal:py3.11.11-gdal3.9.2
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# 6) Copy the rest of your code
COPY . .

# 7) Expose port 8080 (Cloud Run default)
EXPOSE 8080

# 8) Final command - run gunicorn with Uvicorn workers
CMD ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:${PORT}"]