version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - REDIS_URL=${UPSTASH_REDIS_URL}
      - PYTHONUNBUFFERED=1
      - PORT=8080
    depends_on:
      worker:
        condition: service_started
    volumes:
      - ./:/app
      - api_data:/data
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    environment:
      - REDIS_URL=${UPSTASH_REDIS_URL}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
      - worker_data:/data
    healthcheck:
      test: ["CMD", "celery", "-A", "tasks.worker_tasks", "inspect", "ping"]
      interval: 180s
      timeout: 120s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  api_data:
  worker_data: