name: sunlink
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pillow
  - aiohttp
  - celery
  - python-dotenv
  - fastapi
  - gotrue
  - numpy
  - pydantic
  - pyproj
  - rasterio
  - redis
  - requests
  - supabase
  - gunicorn
  - uvicorn
  - pip
  - gdal
