apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunlink-worker-deployment
  labels:
    app: sunlink-worker
spec:
  selector:
    matchLabels:
      app: sunlink-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sunlink-worker
    spec:
      containers:
        - name: sunlink-worker
          image: us-central1-docker.pkg.dev/solarflux-harmony/sunlinkai-artifacts/sunlink-worker:latest
          env:
            - name: UPSTASH_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: sunlinkai-secrets
                  key: UPSTASH_BROKER_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: sunlinkai-secrets
                  key: SUPABASE_KEY
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sunlinkai-secrets
                  key: SUPABASE_URL
            - name: STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: sunlinkai-secrets
                  key: STORAGE_BUCKET_NAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: sunlinkai-secrets
                  key: API_KEY
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"