apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunlink-api-deployment
  labels:
    app: sunlink-api
  annotations:
    prometheus.io/scrape: "true" # Enable Prometheus scraping
    prometheus.io/port: "8080" # Prometheus metrics port
spec:
  selector:
    matchLabels:
      app: sunlink-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sunlink-api
    spec:
      containers:
        - name: sunlink-api-container
          image: us-central1-docker.pkg.dev/solarflux-harmony/sunlinkai-artifacts/sunlink-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10