apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sunlink-worker-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sunlink-worker-deployment
  minReplicas: 0
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: task_queue_depth
        target:
          type: AverageValue
          averageValue: "5"