apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunlink-worker-deployment
  labels:
    app: sunlink-worker
spec:
  selector:
    matchLabels:
      app: sunlink-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sunlink-worker
    spec:
      containers:
        - name: sunlink-worker
          image: gcr.io/solarflux-harmony/sunlink-worker:latest
          env:
            - name: UPSTASH_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: sunlink-worker-secrets
                  key: UPSTASH_BROKER_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: sunlink-worker-secrets
                  key: SUPABASE_KEY
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sunlink-worker-secrets
                  key: SUPABASE_URL
            - name: STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: sunlink-worker-secrets
                  key: STORAGE_BUCKET_NAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: sunlink-worker-secrets
                  key: API_KEY
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
